Azure/azure-diskinspect-service

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/GuestFishWrapper.py, pyServer/manifests/linux/diagnostic, pyServer/manifests/windows/diagnostic
* Adding collection for ManagedIdentify extension log files 
* fixing minor typo in log file header info
=> Adding collection for ManagedIdentity extension log files 

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/eg, pyServer/manifests/windows/eg
I added capture for DHCP events, and I alphabetized the list of events.
=> windows: capture DHCP information

conf/nginx.conf, pyServer/AzureDiskInspectService.py
Adds a health query endpoint (/health) that can be requested through a HTTP GET.
=> Add health query endpoint.

Dockerfile, env.sh, pyServer/AzureDiskInspectService.py, pyServer/main.py, scripts/run.sh
Updates to improve telemetry for service, to use AppInsights
=> Updates to improve telemetry for service

pyServer/manifests/windows/diagnostic
got some CRIs (58648795) where customer messed up with CommonAgentConfig.config - so would be a good idea to collect it too
=> Collect WinGA CommonAgentConfig.config too

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/freebsd/diagnostic, pyServer/manifests/freebsd/normal, pyServer/manifests/linux/eg, tests/test_config.json
Remove /etc/fstab in few more manifests and update tests.
=> Update a few more files and test after removal of /etc/fstab

pyServer/AzureDiskInspectService.py, pyServer/KeepAliveThread.py
- moved logging line after we initialize sessionId so that we get it in the telemetry
- fix for #34 - End of Central Directory record could not be found
=> Change to correct zip corruption issue

pyServer/GuestFishWrapper.py
Run CredScan with only diskinspectsearchers.xml.
=> Update CredScan Command

pyServer/GuestFishWrapper.py, tests/inspection_tests.py, tests/test_config.json
Adding new response header "InspectionMetadata-Partial-Result" to indicate if inspection was aborted by timeout.
=> Adding new response header "InspectionMetadata-Partial-Result"

.travis.yml
- Increasing travis wait time due to buddy build timeout.
=> Increasing travis wait time due to buddy build timeout.

pyServer/AzureDiskInspectService.py, pyServer/GuestFishWrapper.py, tests/inspection_tests.py, tests/test_config.json
-  Auto-trim keep-alive timeout to reserve time for zip archiving
- Added tracing for time elapsed during zip archiving
- Updated unit tests
=>  Auto-trim keep-alive timeout to reserve time for zip archiving

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/agents, pyServer/manifests/linux/diagnostic
Adding the collection of waagent_status.json file from Linux Guest Agent.
=> Adding collection for WAAgent_status.json file

pyServer/GuestFS.py
Add subprocess STDOUT to stderr and log it when exception occure. 
Raise exception from None when retry to avoid duplicate exception.
=> Add subprocess STDOUT to stderr and log it when exception occure

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/aks, pyServer/manifests/windows/aks
Log Collection for AKS Service
=> Log Collection for AKS Service 

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/aks
Create new branch in base repo to merge from fork branch. 
**travis don't support ci-cd from fork repos.
=> Add files in AKS manifests

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/sql-iaas
- Fix glob pattern for sql server logs to capture filenames without extension. Eg. ERRORLOG
- Add Sql Server bootstrap logs which may will be helpful for diagnosing SqlIaaS extension enable issues
=> Additional logs and fixes for sql-iaas

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/sql-iaas
Update sql iaas manifest to include bootstrap summary and pick the compressed cab file instead of Detail.txt
=> Update sql-iaas manifest for bootstrap logs

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/diagnostic, pyServer/manifests/linux/eg
18.04 - 
lrwxrwxrwx 1 root root 39 Feb  4 18:28 resolv.conf -> ../run/systemd/resolve/stub-resolv.conf
16.04 (AKS)
lrwxrwxrwx 1 root root 29 Jan  7 08:14 resolv.conf -> ../run/resolvconf/resolv.conf
=> resolv.conf link diff between 16.04 and 18.04

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/dump
New manifest for collecting \Windows\memory.dmp file
=> dump manifest

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/servicefabric, pyServer/manifests/windows/agents, pyServer/manifests/windows/diagnostic, pyServer/manifests/windows/min-diagnostic, pyServer/manifests/windows/normal, pyServer/manifests/windows/sql-iaas, pyServer/manifests/windows/windowsupdate
Updated manifest files for perf change
=> manifestchanges

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/hdinsight
=> Update HDInsight manifest

pyServer/AzureDiskInspectService.py, tests/inspection_tests.py, tests/test_config.json
Use absolute storage blob uri if found in requestUri else generate it based on storageaccount and cloud environment endpoints
=> Use absolute storage blob uri if found in requestUri

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/aks
Collect Azure NPM logs for AKS on Linux
=> Copy azure npm logs on Linux for AKS

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/aks
we changed the source branch from forked branch to current repo, the original PR is https://github.com/Azure/azure-diskinspect-service/pull/183
=> add AKS Windows containerd log into disk inspector

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/aks
=> AKS: Remove k8s config

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/diagnostic
Product Backlog Item 10310994: axelg to add "Bitlockerextension.log" to the Azure Disk Inspect Service
adding the Bitlocker extension log for Azure Security team
/WindowsAzure/Logs/Plugins/Microsoft.Azure.Security.AzureDiskEncryption/*/BitlockerExtension.log
=> Axelg bitlocker

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/supportability/windows/aks
collect Windows CCGPlugin logs in disk inspector
C:/windows/system32/winevt/Logs/Microsoft-Windows-Containers-CCG%4Admin.evtx
=> AKS: collect Windows CCGPlugin logs in disk inspector

Dockerfile, pyServer/AzureDiskInspectService.py
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python
=> Upgrade Azure Storage Blob library to v12

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/monitor-mgmt, pyServer/manifests/windows/monitor-mgmt
Updated monitor-mgmt log files for both Linux and Windows to collect logs for new features
=> updated Windows and Linux files for monitor-mgmt

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/aks
Need to collect one more event log for AKS Windows CCGPlugin events.
=> AKS: Collect Windows CCGAKVPlugin logs

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/linux-bootconfig, pyServer/manifests/linux/linux-repoconfig
Fixed typo in linux-bootconfig and additions to linux-repoconfig and refreshed manifest docs
=> Fixed typo in linux-bootconfig and additions to linux-repoconfig

Dockerfile, pyServer/AzureDiskInspectService.py, pyServer/main.py
**First PR as part of migrating app-insights based telemetry pipeline to mdsd.**
- ​Change python root logger formatter to Json Formatter, which emits all log records into json format to stream/console and file
- Create request filter to add contextual info (RequestId, SessionId) of each request to log records using thread local
- Create 3 child loggers from root logger to keep track of Trace Event logging, ApiQoS logs and Metric logs for each requests.
- Format each log message as well other attributes part of message into json structure
*Following PR will contain cleanup for the app-insights references
=> Update logging to process it through MDSD

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/aks
Collect kubelet bootstrap-config in Windows nodes
=> AKS: Collect kubelet bootstrap-config in Windows nodes

docs/manifest_by_file.md, docs/manifest_content.md, manifests/windows/diagnostic
Add new file subdirectory to manifest, needs credscan
=> Add RunCommandHandlerWindows/*/*.log to manifest

docs/manifest_by_file.md, docs/manifest_content.md, manifests/windows/agents, manifests/windows/diagnostic, manifests/windows/eg, manifests/windows/normal, manifests/windows/vmdiagnostic, manifests/windows/windowsupdate
… it have chances to contain customer's sensitive data
=> Remove /AzureData/CustomData.bin collection from windows manifests as  it have chances to contain customer's sensitive data

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/monitor-mgmt, manifests/windows/monitor-mgmt
Adding entries to monitor-mgmt manifest that Guest Configuration CSS team is requesting.
=> Guestconfigmanifestupdates

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/crashdump, manifests/linux/diagnostic
Adding collection of /etc/crypttab on Diag report and a report for crash dump analysis
=> Adding collection of /etc/crypttab on Diag report and a report for crash dump analysis

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/diagnostic
Adding support to collect logs regarding pacemaker clusters.
=> Adding pacemaker cluster logs to report

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/diagnostic, manifests/linux/linux-repoconfig
Added files in /etc/pam.d/ to Diagnostic reports, those are small text files that compress quite well.
Added the /var/log/rhuicheck.log file to the linux-repoconfig report.
=> Reposconfig

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/diagnostic
Add 'll,/etc/yum.repos.d' to diagnostic manifest
This is to enable some new insights for Linux machinese
=> Add 'll,/etc/yum.repos.d' to diagnostic manifest

docs/manifest_by_file.md, docs/manifest_content.md, manifests/windows/diagnostic, manifests/windows/windowsupdate
echo,### App Install ###
copy,/Windows/inf/setupapi.app.log
copy,/Windows/Logs/MoSetup/MoSetup.log
copy,/$Windows.~BT/Sources/Panther/CompatData*.xml
copy,/$Windows.~BT/Sources/Panther/miglog.xml
copy,/$Windows.~BT/Sources/Rollback/setuperr.log
copy,/$Windows.~BT/Sources/Rollback/diagerr.xml
copy,/$Windows.~BT/Sources/Rollback/diagwrn.xml
=> Adding additional files to manifests for windows update and diagnostics

docs/manifest_by_file.md, docs/manifest_content.md, manifests/windows/diagnostic
Based on feedback - AVD team had additional logs to collect
=> Product Backlog Item 33004278: IID - additional events to help CloudPC and AVD

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/aks
Backlog work item 134055: [AKS Log Collector] AKS Log Collector to collect the NVidia fabricmanager log
[AKS Log Collector] AKS Log Collector to collect the NVidia fabricmanager log
=> Collect NVidia FabricManager for AKS
