Azure/azure-diskinspect-service

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/agents, pyServer/manifests/linux/site-recovery, pyServer/manifests/windows/site-recovery, tests/test_config.json
PR is for the addition of the "site-recovery" manifest.  This will collect the files needed to troubleshoot issues with [Azure Site Recovery](https://azure.microsoft.com/en-us/services/site-recovery), as specified by members of the ASR engineering and support teams.
=> Adding site-recovery manifest

pyServer/AzureDiskInspectService.py, pyServer/GuestFS.py, pyServer/GuestFishWrapper.py, tests/inspection_tests.py, tests/test_config.json
- add logging of HOSTING_INSTANCE environment variable
- ensuring exceptions produced by the http handler have custom telemetry properties that aid in diagnosis
- revise error handling of failures to start() guestFish to diagnose 3 common error conditions by explicitly doing a http GET with SAS
- adjusting the exception handling in the http handler to not produce exception logging or consider the service as unhealthy due to these types of errors 
- adding tests for these 3 common error conditions
- correcting minor whitespace issues
=> Improve telemetry for exceptions and handling of common errors

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/agents, pyServer/manifests/linux/diagnostic
CustomScript decided to go its own way, and this has defeated common
expectations. I will eventually fix this, but in the interim it would be
nice to collect this file. The Site-Recovery manifest can be used if
necessary to collect the appropriate data.
=> Collect /var/log/custom-script/handler.log

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/diagnostic
Collect the CommonAgentConfig.config from WinGA
Collect the CSE logs for Windows
Also ran the parse_manifest.py to update the doc files
modified:   docs/manifest_by_file.md
modified:   docs/manifest_content.md
modified:   pyServer/manifests/windows/diagnostic
=> Noticed that we weren't pulling CustomScriptExtension logs

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/workloadbackup, pyServer/manifests/windows/workloadbackup
Adding manifest for WorkloadBackup extension to get logs, config for the WorkloadBackup extension.
1. Added in linux
2. Added in Windows
3. Updated documentation
=> Adding manifest for WorkloadBackup

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/diagnostic
agentsManifest is in the agents manifest, so no need to have it here too.
=> remove agentsManifest from diagnostic

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/diagnostic, pyServer/manifests/linux/normal
Temporarily disable /etc/fstab data collection as they can contain AzureFileShare plaintext secrets. The collection of this file will be back once we have added redacting logic for the known issue.
=> Disable fstab collection temporarily.

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/diagnostic, pyServer/manifests/linux/eg
Add the dhcp lease file for the wicked network manager to the diagnostic and eg manifests.  Wicked is used by SLES 12.
=> Add wicked lease

pyServer/AzureDiskInspectService.py, pyServer/KeepAliveThread.py
- Add HOSTNAME environment variable to metrics emitted for alerting
- Adding HOSTNAME(~Role) and Metadata.Name(~RoleInstance) data to a global attribute available in the Python AppInsights SDK which is also picked up by the Geneva connector 
- Adding explicit catch for BrokenPipe exception
- Minor change to HTTP response code to more easily identify bad requests
=> Adding HOST information to logging and metrics

Dockerfile, docs/manifest_by_file.md, docs/manifest_content.md, env.sh, pyServer/GuestFishWrapper.py, pyServer/manifests/freebsd/diagnostic, pyServer/manifests/freebsd/normal, pyServer/manifests/linux/diagnostic, pyServer/manifests/linux/eg, pyServer/manifests/linux/normal, scripts/run.sh, tests/test_config.json
- If Credential Scanner exists it is added to the docker container as a volume. Files are scanned and any files which include any secret (ex passwords/SAS keys) are deleted before being zipped.
- If Credential Scanner does not exist, disk inspection continues to run as before with an additional warning log.
- fstab has been added back. Initially removed [here](https://github.com/Azure/azure-diskinspect-service/commit/2753d0efdaa063aebe26a307fc7c434774931d21).
- Parse manifests have been updated.
=> Credential Scanner Integration + Re-adding fstab

pyServer/GuestFishWrapper.py, pyServer/KeepAliveThread.py
- Kill CredScan from KeepAliveThread if overall runtime has timed-out.
- Check for any created output file on error and remove any discovered secrets.
- Check if overall timeout has occurred before running CredScan.
=> Credscan Timeout

pyServer/GuestFishWrapper.py
- Add additional details about what secrets are discovered which files and how many times to CredScan logging. Each file containing a secret has its own log line.
- Ex: CredentialScanner: Detailed - File: path/to/file.log, Secrets: [SASkey 2, FstabPassword 1]
- Added directory size and file count to CredScan statistics.
- Moved CredScan duration into statistics log.
- New statistics log: OperationalLog: CredentialScanner: Statistics - No. Scanned Files: 5, Scanned Directory Size: 500 bytes, Operation duration: 5 seconds, No. Removed: 3, Removed File List: [file1, file2, file3]
- Added check for CredScan output file on local timeout. Discovered secrets will now be removed.
Edit:
- Negative error codes are due to signals (SIGTERM, SIGABORT). Added special handling to log the signal name …
=> Additional Credscan logging and statistics

pyServer/AzureDiskInspectService.py, pyServer/GuestFishWrapper.py
- Added POST parameter for credscan: `-d "credscan=true"` will run disk inspect with credscan, false or non-existent option will run disk inspect without credscan.
- Modified credential scanner to redact lines containing secrets in files < 1MB. Larger files will be removed as previously. Added logging to differentiate between files which got removed and files which had secrets redacted.
=> Disk Inspect POST option for Cred Scan

conf/nginx.conf
Removed all `allow` and `deny` rules from nginx server configuration.
=> Remove nginx IP rules

pyServer/GuestFishWrapper.py
- Fix a bug with stats around removed files vs redacted files.
- Always write CredScan Stats to file. Added writing to file when no secrets have been found
=> Fix CredScan logging

pyServer/AzureDiskInspectService.py, pyServer/main.py
Release Name added to Applnsights customDimensions.
If not found in environment variables, default is "AzureDiskInspect-Release-MANUAL".
Also fixed check for container version in env - previously this would error if it did not exist.
=> Add Release Name Logging

pyServer/AzureDiskInspectService.py, pyServer/KeepAliveThread.py, tests/inspection_tests.py, tests/test_config.json
Parameterizing KeepAliveThread MaxTimeout so it can be overridden. This is so that certain types of calls that go through ACIS (for example, requests made from ASC Portal) don't have to timeout and will run to completion. Default remains 19 mins when new param is not given.
=> Parameterizing KeepAliveThread MaxTimeout

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/diagnostic
Customers may set a PROXY server in machine.config, which influeces the
guest agent.  It is difficult to diagnose without this file.
=> collect machine.config

.travis.yml, Dockerfile, docs/readme.md, docs/result_upload.md, pyServer/AzureDiskInspectService.py, tests/inspection_tests.py, tests/test_config.json
* Adding blob url based data transport support.
* Adding unit tests to cover Linux/Windows and invalid inputs for blob upload scenario.
* Adding delay in unit test to allow service cleanup.
* Improved exception handling around blob upload in case underlying Storage clinet library throws.
Added time tracking for blob upload activity in telemetry.
Updated comments in response to PR comments.
* Adding retry around blob upload and leaving 'KeepAlive' on during blob upload.
* Fixing typos and commments.
* Adding new .md file to describe usage.
* Added result blob validation and updated invalid blob sas url input handling.
* Added Travis config changes.
=> Adding support to use Blob SAS Url to perform data transport (#69)

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/agents, pyServer/manifests/linux/diagnostic
The VM Agent v2.2.32  changed the location of the extension logs from, for example,
/var/log/azure/Microsoft.OSTCExtensions.VMAccessForLinux/1.4.7/extension.log
to
/var/log/azure/Microsoft.OSTCExtensions.VMAccessForLinux/extension.log
Adding new path to capture logs from older and newer agents.
=> Add new path for extension logs

pyServer/AzureDiskInspectService.py, pyServer/GuestFishWrapper.py
- Open CredScan flagged files with UTF-8 encoding to address 'ascii codec can't decode' issue
- Adding catch all exception handling and strack trace printing
=> Open CredScan flagged files with UTF-8 encoding to address 'ascii codec can't decode' issue

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/GuestFishWrapper.py, pyServer/manifests/windows/diagnostic, pyServer/manifests/windows/windowsupdate
* For os type 'Windows' use "case_sensitive_path" function to remove the case sensitivity while looking for the path in disk.
* Remove duplicate paths with different case from manifest (windows/diagnostics), which are added to prevent "File not found"
=> Remove case sensitivity for Windows os paths

Dockerfile, conf/sources.list
- Change Dockerfile to use the fork which contain merge of Official libguest upstream and fork - https://github.com/CraigWiand/libguestfs
(This will be change to official libguest upstream after "query string" changes merge to official branch)
- Updates in Dockerfile needed for above change - upgrade base OS ubuntu version to 18.04, add required new packages
=> Use latest libguestfs version from official upstream

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/diagnostic, pyServer/manifests/linux/eg
For Ubuntu 18.04  /etc/network info- the ifup and ifdown functionality is deprecated and it now uses netplan
=> Add netplan config in diagnostic and eg manifests for Ubuntu 18.04

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/diagnostic
adding the AADLoginForWindows logs as per the ask below
From: David Everett
Sent: Thursday, September 12, 2019 4:51 PM
To: Gabriela Limoli Gabriela.Limoli@microsoft.com
Cc: Johnny Coleman johnnyc@microsoft.com; Kari Lacobee kalaco@microsoft.com
Subject: Inspect Iaas Disk Diagnostic not capturing AADLoginForWindows agent logs
Hi Gabriella,
The Inspect Iaas Disk diagnostic collects logs from the AADLoginForLinux VM, but its not capturing the logs from AADLoginForWindows.
• Can we have this diagnostic capture any log that is greater than 4k under C:\WindowsAzure\Logs\Plugins\Microsoft.Azure.ActiveDirectory.AADLoginForWindows\0.3.1.0?
o Can we have it find the latest version folder in the path in the event this changes over time?
Thanks,
David
=> adding AADLogs to Diagnostics Manifest

.travis.yml, Dockerfile
Set Azure Storage Blob package version to 1.4.0 to prevent it to pick default latest version, which is not compatible.
=> Set Azure Storage Blob package version to 1.4.0 

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/hdinsight
Add a minimal set of log files to hdinsight manifest
to be retrieved along with the existing set of
configuration files.
=> Update hdinsight manifest with log files

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/diagnostic, pyServer/manifests/windows/dump
Removed the two most expensive calls which are wildcards for infrequently used Windows guest agent  files that if needed, are already collected by the agents manifest.
=> Optimize diagnostic manifest by removing two most expensive calls

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/freebsd/agents, pyServer/manifests/freebsd/diagnostic, pyServer/manifests/linux/agents, pyServer/manifests/linux/diagnostic
Add HandlerState and HandlerStatus file to Inspect IaaS Disk Tool. This is needed by the Linux Guest Agent to debug the last extension state.
=> Add HandlerState and HandlerStatus file to Inspect IaaS Disk Tool

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/aks
adding kubelet config file to AKS manifest
CRI 190534195 - where the kubelet config file is not parsing correctly from YAML to JSON - causing Windows node pool to fail creating
=> adding kubelet config file to AKS manifest

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/diagnostic
- to get it automatically collected on AKS cases - before customer/AKS deletes the VM.
expected size of the file = 50KB
Background = CRI 191994148 where an AKS with GPU node pool failing to start - and it was deleted as costing too much
=> adding AKS cluster-provision.log file

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/agents, pyServer/manifests/windows/diagnostic, pyServer/manifests/windows/normal, pyServer/manifests/windows/windowsupdate
WinGA install logs to C:\Windows\Panther\VmAgentInstaller.xml to it is important that we collect it for WinGA install troubleshooting. 
Added it to diagnostic, agents, and normal manifests.
=> Add WinGA install log VmAgentInstaller.xml

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/aks
Backlog work item 6604: Collect nvidia-installer-XYZ.log for AKS cases
for AKS using GPU nodes, they sometimes fail installing the NVidia drivers. We need at least the /var/log/nvidia*.log installer logs to troubleshoot
=> Axelg NVidia logs for AKS

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/diagnostic
There are multiple instances of error.json, each in a different directory. Added a wildcard to handle that. 
Those are very small files and usually do not exist; when they do exist there should be just a few of them (2 or 3).
=> Fix path for error.json

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/sql-iaas
SQL IaaS extension is now available for SQL Linux VMs. Before we announce it public we would like to add ASC support this extension.
=> adding sql-iaas extension logs to ASC.

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/aks
Adding the status file specific to containerd which is used on clusters running k8s v 19+ by default.
File will be similar to impact/size as /var/log/azure/docker-status.log - which is a small file
=> adding containerd status

README.md, docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/aks
We need to collect these logs in AKS Windows nodes for troubleshooting.
C:\CalicoWindows only exists when provisioning AKS Windows nodes for using calico as network policy.
For #175
=> AKS: Collect Calico Windows logs

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/normal
I'm working on creating an Insight for ASC which uses IID. I need ifcfg-eth0 file to be included in the Min-Diagnostic Mode so that we can use this file to create an insight.
=> Adding ifcfg-eth0 to Min-Diagnostic Manifest

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/aks
kubeclusterconfig.json does not contain any credentials but it contains some parameters for trouble shooting, for example, WinDSR=true, WinOverlay=false is included in FeatureGates when enabling WinDSR.
Reference https://github.com/Azure/AgentBaker/pull/800
=> collect kubeclusterconfig.json in AKS Windows nodes

Dockerfile
Fixes some UnicodeEncodingErrors caused by ASCII unable to decode unicode characters in IID
=> Docker Locale set to C.UTF-8

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/agents, pyServer/manifests/linux/diagnostic, pyServer/manifests/linux/eg
New file of the format waagent_status.{0}.json needs to be onboarded to inspect disk.
-  There will be one file at an instance. And the wild card character denoted the incarnation number. When incarnation number changes the file name changes.
- Expected File Size ~5kB
=> Include newfile linux waagent_status.{0}.json for Linux Guest Agent

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/agents, pyServer/manifests/windows/normal
Adds files necessary for VmApps debugging. This applies to Windows and Linux.
VmApp.lockfile - small single-byte file used for synchronization
applicationRegistry.active - contains the list of applications we've installed and their status. Should be no larger than 5 kb.
log files for VmApplication extension - should be similar in length to other extensions, particularly RunCommand
=> Adds files for the VmApp extension

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/windows/diagnostic, pyServer/manifests/windows/vmdiagnostic
Added one line to three files to copy TXT files from the Microsoft.Azure.ActiveDirectory.AADLoginForWindows plugin.
* docs/manifest_by_file.md:
/WindowsAzure/Logs/Plugins/Microsoft.Azure.ActiveDirectory.AADLoginForWindows/\*/\*.t<br>xt | diagnostic, vmdiagnostic 
* docs/manifest_content.md:
diagnostic | copy | /WindowsAzure/Logs/Plugins/Microsoft.Azure.ActiveDirectory.AADLoginForWindows/\*/\*.t<br>xt
* pyServer/manifests/windows/diagnostic:
copy,/WindowsAzure/Logs/Plugins/Microsoft.Azure.ActiveDirectory.AADLoginForWindows/*/*.txt
=> Adding AADLogs (txt) to Diagnostics Manifest

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/aks
[Backlog work item 26393](https://supportability.visualstudio.com/AzureContainers/_workitems/edit/26393): axleg to add the AKSNode extension log into the InspectIaaSDisk manifest for AKS
Adding the AKSNode extension log to Azure Disk Inspect
=> axelg adding AKSNode log

docs/manifest_by_file.md, docs/manifest_content.md, pyServer/manifests/linux/aks
This PR adds CNS logs to diskinspect for AKS. This is necessary because if CNS is crashing, we have no way to get its logs without diskinspect, since CNS is responsible for setting up pod networking, and pod networking is required for things like `kubectl logs azure-cns ...`
=> chore: add CNS logs to diskinspect

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/aks
Fixes AB#15010385 
The AKS manifest has been updated to ``"copy,/var/log/pods/kube-system*/*/*.log*"`` in order to add historical logs that are being written as `` .log.<date-created> ``
There has been also a change to include Cilium and IPAM logs in AKS manifest.
=> The AKS manifest has been updated to include historical logs as well as Cilium and IPAM logs.

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/diagnostic
Adding chrony.conf, imapd.conf and sshd dropin directory as proposed by previous PRs 
Removed references to files in the /run filesystem, since /run is a RAM filesystem and files there are ephemeral, once the OS is down, the files are gone for good.
=> Adding chrony.conf, imapd.conf and sshd dropin directory as proposed by previous PRs 

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/vmdiagnostic
Added: 
- chrony.conf, idmapd.conf and sshd drop-in directory,
- boot configuration files used in RHEL8 and above.
Listed:
- systemd startup configuration files.
Removed:
- files from /run filesystem, /run filesystem is a RAM based one and files will not be available during the IaaS diagnostics collection.
These files facilitate diagnosis of time synchronization, NFS, sshd connectivity and system startup issues.
=> Added conf files for sshd, nfs, time sync and system startup files.

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/aks
**Change set:**
* we don't use Docker anymore
* fixed calico and tigera logs
* added kured
**Issue reproduction:**
The logs were not exported for calico, tigera and kured.
**Test:**
Tested with [kvaps/kubectl-node-shell: Exec into node via kubectl (github.com)](https://github.com/kvaps/kubectl-node-shell) on the vmss in AKS
=> Updated aks manifest

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/diagnostic
The manifest already included the whole /etc/sysconfig/network directory, hence adding individual files to the manifest was adding an extra subdirectory layer causing the /etc/sysconfig/network directory to be copied under the /etc/sysconfig/network/network subdirectory.
=> Removing specific files in /etc/sysconfig/network 

docs/manifest_by_file.md, docs/manifest_content.md, manifests/windows/diagnostic
this is a PR to support collecting Apphealth and VMWatch logs with azure inspect disk service based on CSS team's requirement
=> Add apphealth vmwatch log

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/linux-repoconfig
Ubuntu 24.04 added a new format of apt config with extension .sources.
This is documented here.
https://manpages.ubuntu.com/manpages/oracular/en/man5/sources.list.5.html
=> Adding deb822 format for sources, used in Ubuntu 24.04

docs/manifest_by_file.md, docs/manifest_content.md, manifests/linux/vmdiagnostic
The journal has the most detailed system logs.  This matches the configuration used by the aks manifest to collect it.
=> vmdiagnostic: collect /var/log/journal

docs/manifest_by_file.md, docs/manifest_content.md, manifests/windows/aks
For troubleshooting purposes and TTM reduction.
To mimic collect-windows-logs.ps1, adding the following files to the manifest:
kubeclusterconfig.json
CNI and CNS logs
NVIDIA driver installation logs
WAAGENT logs
last bugcheck minidump*
if less than 10 MBs. A ScheduledTask on the windows node will validate if a minidump exists and if it's less than 10 MBs in size, it'll be copied over to C:/WindowsAzure/Logs/aks/*.dmp
=> Adding AKS Windows logs to IID manifest
